services:
  backend:
    build: ./backend
    container_name: backend-api
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
      - qdrant

  celery-worker:
    build: ./backend
    container_name: celery-worker
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info -P solo
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres-dbx
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redisx
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrantx
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pgdata:
  qdrant_data:
