version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-app-z
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis
      - qdrant

  celery:
    build: .
    container_name: celery-worker-z
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info -P solo
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - api
    restart: on-failure

  postgres:
    image: postgres:15
    container_name: postgres-db-z
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-z
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-z
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  pgdata:
  qdrant_data:
